### ISSUE TITLE
SQL - Conexion

### ISSUE THREAD

**Issue by 3sandy33** [IrvinRubio/PROYECTO2024-12#2]
Enlazar los programas

**Comment by IrvinRubio** [comment]
"""
Integrantes
- Rubio Castellanos Irvin Roberto
- Sandy Jaqueline Rivas Medina

"""
import pymysql


mysql_connection = pymysql.connect(host="localhost",
                                   user="root", password="12345", database="guitarras")

if mysql_connection.open:
    print("MySQL runs")
else:
    print("Error on MySQL")

import pymysql

mysql_connection = pymysql.connect(
    host="localhost",
    user="root",
    password="12345",
    database="guitarras",
    charset="utf8mb4",
    cursorclass=pymysql.cursors.DictCursor
)

if mysql_connection.open:
    print("MySQL runs")
else:
    print("Error on MySQL")

try:
    with mysql_connection.cursor() as cursor:

        cursor.execute("create database guitarras;")
        cursor.execute("use guitarras;")


        cursor.execute("""
        create table MarcasGuitarras (
            id int auto_increment primary key,
            nombre VARCHAR(100) not null,
            pais_origen varchar(50),
            fundada_en int,
            descripcion text
        );
        """)


        cursor.execute("""
            create table ModelosGuitarras (
            id int auto_increment primary key,
            nombre varchar(100) not null,
            marca_id int not null,
            tipo varchar(50),
            lanzamiento year,
            precio decimal(10, 2),
            descripcion text,
            foreign key (marca_id) references MarcasGuitarras(id)
        );
        """)


        cursor.execute("""
        create table PrecioPromedioPorPais (
            id int AUTO_INCREMENT primary key,
            pais varchar(50) not null,
            precio_promedio decimal(10, 2) not null
        );
        """)


        cursor.executemany("""
        insert into MarcasGuitarras (nombre, pais_origen, fundada_en, descripcion)
        values (%s, %s, %s, %s)
        """, [
            ('Segovia', 'Estados Unidos', 1946, 'Conocida por su icónica Stratocaster y Telecaster.'),
            ('Mccartney', 'Estados Unidos', 1902, 'Famosa por la Les Paul y SG.'),
            ('Sambors', 'Japon', 1957, 'Popular entre guitarristas.'),
            ('Smiger', 'Japon', 1887, 'Fabricante versátil de guitarras acusticas y electricas.'),
            ('Divine', 'Estados Unidos', 1985, 'Conocida por guitarras premium con gran detalle.')
        ])

        cursor.executemany("""
        insert into ModelosGuitarras (nombre, marca_id, tipo, lanzamiento, precio, descripcion)
        value (%s, %s, %s, %s, %s, %s)
        """, [
            ('Stratocaster', 1, 'Electrica', 1954, 1200.00, 'Una de las guitarras mas iconicas de Fender.'),
            ('Les Paul', 2, 'Electrica', 1952, 2500.00, 'Modelo legendario de Gibson con sonido calido.'),
            (
            'RG550', 3, 'Electrica', 1987, 1000.00, 'Guitarra de alto rendimiento de Ibanez, popular en rock y metal.'),
            ('FG800', 4, 'Acustica', 2016, 200.00, 'Modelo asequible y versatil de Yamaha.'),
            ('Custom 24', 5, 'Eléctrica', 1985, 3500.00, 'El modelo insignia de PRS con excelente diseño y tono.')
        ])


        cursor.execute("""
        insert into PrecioPromedioPorPais (pais, precio_promedio)
        select mg.pais_origen as pais, 
               AVG(mguit.precio) as precio_promedio
        from MarcasGuitarras mg
        join ModelosGuitarras mguit on mg.id = mguit.marca_id
        group by mg.pais_origen;
        """)


        cursor.execute("SELECT * FROM PrecioPromedioPorPais;")
        results = cursor.fetchall()

        print("Precio promedio por pais:")
        for row in results:
            print(row)


    mysql_connection.commit()

finally:

    mysql_connection.close()
    print("Conexion cerrada.")
