### ISSUE TITLE
Dashboard_1

### ISSUE THREAD

**Issue by 3sandy33** [IrvinRubio/PROYECTO2024-12#3]
Agregamos e investigamos los datos

**Comment by IrvinRubio** [comment]
import pandas as pd
import dash_bootstrap_components as dbc
import plotly.express as px
from dash import dcc, html, callback, Input, Output
def dashboard_basico():
    data = pd.read_csv("datasets/GUITARRAS.csv")
    fig = px.line(data, y=["Marca", "Modelo","PrecioPromedio"],
                  title="Precio Promedio", template="plotly_dark")
    fig_box = px.box(data, y=["PrecioPromedio"],
                     title="Precio Promedio",
                     template="plotly_dark")
    blanco = {"color": "Lightblue","text-align": "center"}
    body = html.Div(
        [

            dbc.Row([
                html.H2("Guitarras Valdez", style=blanco),
                dcc.Dropdown(options=["all", "Marca", "Modelo", "PrecioPromedio"],
                             value="all", id="addCompany"),
                html.Hr(),
            ]),
            dbc.Row([

                dbc.Col(dcc.Graph(figure=fig_box, id="figBox"),width=5)
            ])
        ],  style={"background-color": "#000000"}
    )
    return body
@callback(
    Output(component_id="figLine", component_property="figure"),
    Output(component_id="figBox", component_property="figure"),
    Input(component_id="addCompany", component_property="value")
)
def update_graficas(value_company):
    print(value_company)
    data = pd.read_csv("datasets/GUITARRAS.csv")
    col_chosen = value_company
    if col_chosen == "all":
        col_chosen = ["PrecioPromedio"]

    fig = px.line(data, y=col_chosen,
                  title="Marcas mas Vendidas", template="plotly_dark")
    fig_box = px.box(data, y=col_chosen,
                     title="Modelos mas Vendidos",
                     template="plotly_dark")
    return fig, fig_box
